// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>ProductsSchema</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace ProductsSchema {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class products {
        
        private List<productsProduct> productField;
        
        public products() {
            this.productField = new List<productsProduct>();
        }
        
        public List<productsProduct> product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    public partial class productsProduct {
        
        private string idField;
        
        private string nameField;
        
        private string eanField;
        
        private string ean1Field;
        
        private string ean2Field;
        
        private string descriptionField;
        
        private List<string> imagesField;
        
        private string priceField;
        
        private string suggested_priceField;
        
        private string vatField;
        
        private string weightField;
        
        private string stockField;
        
        private string categoryField;
        
        private string manufacturerField;
        
        private string manufacturer_codeField;
        
        private byte guaranteeField;
        
        private string availableField;
        
        private string sexField;
        
        public productsProduct() {
            this.imagesField = new List<string>();
        }
        
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
            }
        }
        
        public string ean1 {
            get {
                return this.ean1Field;
            }
            set {
                this.ean1Field = value;
            }
        }
        
        public string ean2 {
            get {
                return this.ean2Field;
            }
            set {
                this.ean2Field = value;
            }
        }
        
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("image", IsNullable=false)]
        public List<string> images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        public string suggested_price {
            get {
                return this.suggested_priceField;
            }
            set {
                this.suggested_priceField = value;
            }
        }
        
        public string vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
        
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        public string stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
            }
        }
        
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        public string manufacturer_code {
            get {
                return this.manufacturer_codeField;
            }
            set {
                this.manufacturer_codeField = value;
            }
        }
        
        public byte guarantee {
            get {
                return this.guaranteeField;
            }
            set {
                this.guaranteeField = value;
            }
        }
        
        public string available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
    }
}
